- name: Create a resource group
  shell: |
      az group create --name amcop-cluster-group --location eastus
  register: cls_output
- debug: var=cls_output.stdout_lines

- name: Create a vnet for connecting with the KUD cluster
  shell: |
      az network vnet create  --resource-group amcop-cluster-group --name amcop-aks-vnet --address-prefix 10.20.0.0/16 --subnet-name amcop-subnet --subnet-prefix 10.20.0.0/24
  register: vn_output
- debug: var=vn_output.stdout_lines

- name: Create cluster
  shell: |
    cd {{amcop_script_folder}}
    ./create_azure_cluster.sh "{{ item.cluster_name }}" 
  register: cls_output
  with_items: "{{ serverList }}"

- debug:
    msg: "{{ item.stdout }}"
  with_items: "{{ cls_output.results }}"

- name: Sleeping for 2 minutes for the cluster to come up
  wait_for: timeout=120

- name: Get cluster credentials
  shell: |
      az aks get-credentials --resource-group amcop-cluster-group --name "{{ item.cluster_name }}" --overwrite-existing
  register: crd_output
  with_items: "{{ serverList }}"

- debug:
    msg: "{{ item.stdout }}"
  with_items: "{{ crd_output.results }}"

- name: Waiting for 10 sec
  wait_for: timeout=10

- name: List all pods and nodes
  shell: |
      kubectl get pods --all-namespaces
      kubectl get nodes
  register: ls_output
- debug: var=ls_output.stdout_lines
