apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
   name: network-attachment-definitions.k8s.cni.cncf.io
spec:
   group: k8s.cni.cncf.io
   scope: Namespaced
   names:
      plural: network-attachment-definitions
      singular: network-attachment-definition
      kind: NetworkAttachmentDefinition
      listKind: NetworkAttachmentDefinitionList
      shortNames:
      - net-attach-def
   versions:
   - name: v1
     served: true
     storage: true
     schema:
        openAPIV3Schema:
           type: object
           properties:
             spec:
                type: object
                properties:
                   config:
                     type: string

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: f5gc-gnbsim-n1n2
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eno2",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": "172.16.10.10/24",
                        "gateway": "172.16.10.1"
                }
        ]
      }
    }'

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: f5gc-gnbsim-n3
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eno2",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": "192.168.10.10/24",
                        "gateway": "192.168.10.1"
                }
        ]
      }
    }'
