apiVersion: v1
kind: Namespace
metadata:
  name: dp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauthproxy
  namespace: dp
  labels:
    app: oauthproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauthproxy
  template:
    metadata:
      labels:
        app: oauthproxy
    spec:
      containers:
      - name: oauthproxy
        image: phx.ocir.io/oicpaas1/sumagant/oauthproxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: k8s-pull
      volumes:
      - name: dp-config-volume
        configMap:
          name: dp-config
---
kind: Service
apiVersion: v1
metadata:
  name: oauthproxy-service
spec:
  selector:
    app: oauthproxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8090
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oauthproxy-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - www.sumanganta.com
    secretName: sumanganta-domain-tls
  rules:
  - http:
      paths:
      - path: /p
        backend:
          serviceName: oauthproxy-service
          servicePort: 80
