- name: Clone OOM GIT Repo and Delete charts
  shell: |
    if [ {{oom_branch}} != "" ]
    then
      git clone http://gerrit.onap.org/r/oom --recurse -submodules -b {{oom_branch}}
    else
      git clone http://gerrit.onap.org/r/oom --recurse -submodules
    fi
    chown -R {{ansible_ssh_user}}:{{ansible_ssh_user}} oom
    cd oom/kubernetes
    cp -R ./helm/plugins/ ~/.helm
    rm -rf cds/charts/cds-command-executor/
    rm -rf sdc/charts/sdc-dcae-be/
    rm -rf sdc/charts/sdc-dcae-dt/
    rm -rf sdc/charts/sdc-dcae-fe/
    rm -rf sdc/charts/sdc-dcae-tosca-lab/
    rm -rf sdc/charts/sdc-wfd-be/
    rm -rf sdc/charts/sdc-wfd-fe/
    rm -rf so/charts/so-openstack-adapter/
    rm -rf so/charts/so-sdnc-adapter/
    rm -rf so/charts/so-vfc-adapter/
    rm -rf so/charts/so-vnfm-adapter/
    rm -rf so/charts/so-ve-vnfm-adapter/
    rm -rf multicloud/charts/multicloud-pike 
    rm -rf multicloud/charts/multicloud-azure 
    rm -rf multicloud/charts/multicloud-windriver 
    rm -rf multicloud/charts/multicloud-prometheus 
    rm -rf multicloud/charts/multicloud-vio
    rm -rf multiccloud/charts/multicloud-fcaps
    rm -rf multicloud/charts/multicloud-starlingx/

- name: Copy alite_oom_override.yaml file
  copy:
    src: "{{ oom_override_file }}"
    dest: "{{oom_override_file_dest}}"
    mode: "755"
    owner: "{{ansible_ssh_user}}"
  when: oom_override_file != ""

#TODO helm 3
#- name: Configure Chartmuseum
#- name: Install helm plugin for push
#- name: Start chartmusem local repo
#- name: Add local to chartmuseum

- name: Install helm packages
  become: yes
  become_method: sudo
  shell: |
    cd /home/{{ansible_ssh_user}}/oom/kubernetes;
    if [ {{oom_override_file}} != "" ]
    then
      nohup sudo helm deploy dev local/onap --namespace onap -f  alite_oom_override.yaml -f onap/resources/environments/public-cloud.yaml --set global.masterPassword=onap --verbose --timeout 2000 > $HOME/helm_deploy.log 2>&1 &
    else 
      nohup sudo helm deploy dev local/onap --namespace onap -f onap/resources/environments/public-cloud.yaml --set global.masterPassword=onap --verbose --timeout 2000 > $HOME/helm_deploy.log 2>&1 &
    fi
