# Default values for sink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  sinkrepo: rtsood/onap-vfw-demo-sink
  sinktag: 0.2.0
  pullPolicy: IfNotPresent
  darkstatrepo: electrocucaracha/darkstat
  darkstattag: latest

nameOverride: ""
fullnameOverride: ""

service:
#serivce port value for sink service
  type: NodePort
  ports:
    port: 667
    nodePort: 30667

nodeSelector: {}

tolerations: []

affinity: {}

global:
  #Networks
  unprotectedNetworkName: unprotected-private-net
  protectedPrivateNetCidr: 192.168.10.0/24
  protectedPrivateNetGw: 192.168.10.1/24

  onapPrivateNetworkName: onap-private-net
  onapPrivateNetCidr: 10.10.0.0/16
  onapPrivateNetGw: 10.10.0.1/16

  protectedNetworkName: protected-private-net
  protectedNetCidr: 192.168.20.0/24
  protectedNetGwIp: 192.168.20.100
  protectedNetGw: 192.168.20.100/24

  #vFirewall container
  vfwPrivateIp0: 192.168.10.3/24
  vfwPrivateIp1: 192.168.20.2/24
  vfwPrivateIp2: 10.10.100.3/24
  #Packetgen container
  vpgPrivateIp0: 192.168.10.2/24
  vpgPrivateIp1: 10.0.100.2/24
  #Sink container
  vsnPrivateIp0: 192.168.20.3/24
  vsnPrivateIp1: 10.10.100.4/24
  vsnPrivatePort0: eth1
  vsnPrivatePort1: eth2

  #########
  ovnMultusNetworkName: ovn-networkobj
  demoArtifactsVersion: 1.5.0
  dcaeCollectorIp: 10.0.4.1
  dcaeCollectorPort: 8081
