- name: Install Config Service.
  shell: |
    cd {{configsvc_path}}
    helm install configsvc configsvc -n {{k8s_namespace}}
  register: conf_output
- debug: var=conf_output.stdout_lines

- name: Waiting for a few seconds for the configuration service to come up
  wait_for: timeout=30

- name: Install AMCOP UI.
  shell: |
    cd {{emco_ui_folder}}
    helm install emcoui emcoui -n {{k8s_namespace}}
  register: ui_output
- debug: var=ui_output.stdout_lines
