- include_tasks: common/install_oc_client.yaml

- name: Configuring oc client and installing AMCOP
  shell: |
    #!/bin/bash
    oc login --insecure-skip-tls-verify={{opshift_oc_insecure_flag}} -u {{opshift_oc_user_name}} -p {{opshift_oc_password}} {{opshift_oc_url}}
    oc adm policy add-scc-to-group anyuid system:authenticated
  register: oc_login_output
- debug: var=oc_login_output.stdout_lines

- fail: msg="Login has failed. Please check the credentials and the url"
  when: oc_login_output.stdout is search("Login failed")

#- include_tasks: common/install_helm_2.yaml
#- include_tasks: common/onap4k8s_repo.yaml
- include_tasks: emco/include_emco_components_for_cloud.yaml
#- include_tasks: emco/install_smo.yaml

#- name: Expose AMCOP UI Deployment
#  shell: |
#     kubectl get pods -n {{k8s_namespace}}
#     kubectl expose deployment emcoui --type=LoadBalancer --name=emcoui-gui -n {{k8s_namespace}}
#  register: exp_output
#- debug: var=exp_output.stdout_lines

#- name: Sleeping for 2 minutes for the services to come up
#  wait_for: timeout=120

#- name: Get the external IP to access EMCO UI
#  shell: |
#     EXTERNAL_IP=$(echo $(kubectl get svc -n {{k8s_namespace}} | grep emcoui-gui | awk '{ print $4 }'))
#     echo "IP to access the emco GUI: $EXTERNAL_IP"
#  register: ext_output
#- debug: var=ext_output.stdout_lines

