- name: "Checking ansible version >={{ req_ansible_version }} and <={{supported_ansible_version}}"
  assert:
     msg: "Ansible must be >={{req_ansible_version}} and <={{supported_ansible_version}}. Please run prepare_baremetal script to install the correct ansible version "
     that:
       - ansible_version.string is version(req_ansible_version, ">=")
       - ansible_version.string is version(supported_ansible_version, "<=")

- name: "Checking if jq is present"
  stat: path=/usr/bin/jq
  register: jq_present

- name: fail if jq not present
  fail: msg="jq is not installed on this machine. Please run prepare_baremetal script to install jq"
  when: not jq_present.stat.exists
