build:
	$(MAKE) -C guimiddleend build
	$(MAKE) -C configsvc build

deploy:
	$(MAKE) -C guimiddleend deploy 
	$(MAKE) -C configsvc deploy 

all:
	$(MAKE) -C guimiddleend all 
	$(MAKE) -C configsvc all 

clean:
	$(MAKE) -C guimiddleend clean 
	$(MAKE) -C configsvc clean 
